//
//  HHActivity.m
//  校园助手
//
//  Created by hjl on 16/5/8.
//  Copyright © 2016年 hjl. All rights reserved.
//

#import "HHActivity.h"

@implementation HHActivity

- (CGFloat)cellHeight{
    if(!_cellHeight){
        CGFloat margin = 10;
        if(self.content){
            CGSize maxSize = CGSizeMake([UIScreen mainScreen].bounds.size.width - 4 * margin, MAXFLOAT);
            CGFloat cententLableH = [self.content boundingRectWithSize:maxSize options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName : [UIFont systemFontOfSize:14]} context:nil].size.height;
            _cellHeight = cententLableH;
        }
    }
    return _cellHeight + 1 + 20;
}

@end





/*
 {
            "activitySite": "河南理工大学大学生活动中心220",
            "activityTime": 1461411000000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 0,
            "content": "20名演讲达人，一路披荆斩棘、过关斩将，在两百余名选手中脱颖而出，天赋异禀，实力强悍的他们又将为我们带来哪些听觉盛宴呢？让我们拭目以待吧\n\n资深的评委导师团队：马克思主义学院原理教研室主任、哲学博士，郭伶俐教授\n                    资深演讲人，焦作朗诵协会会长秦团长先生\n                    文法学院资深讲师，文法系博士，多次举办演讲培训讲座史玉丰老师\n\n还在不辞辛苦的追网红吗？引颈盼望只为拍下网红回眸一笑吗？完全没有必要！将来的网红就在我们身边！让我们近距离的领略他们的风采吧！\n\n还在因为无法进入CUBA现场而烦心吗？还在为CUBA门票而苦恼吗？ 还在为",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1461403141000,
            "likeCount": 4,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 21048,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 480,
                "url": "http://qiniu.myfriday.cn/o_1ah16nb56596e521c631je5ih7.jpg",
                "width": 360
            }],
            "readCount": 87745,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 20797,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "“联盟杯”理工赛区决赛开赛啦~！",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学演讲与辩论协会",
            "weight": 0
        }, {
            "activitySite": "学苑餐厅东门",
            "activityTime": 1460772000000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 1,
            "content": "为配合学校反邪教工作，提高大学生防邪反邪思想，使大家对邪教怀以警惕之心，向同学们宣传“倡导科学生活方式，拒绝一切邪教活动”的正确思想，故举办此次图文展。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1460220161000,
            "likeCount": 17,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 20211,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 3740,
                "url": "http://qiniu.myfriday.cn/o_1aftu83de1uits3retr1qqb1sol7.jpg",
                "width": 2805
            }],
            "readCount": 182739,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 19958,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "“看图辨邪教，读文正三观” 图文展",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "大学生反邪教协会",
            "weight": 0
        }, {
            "activitySite": "河南理工大学校内",
            "activityTime": 1460044800000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 9,
            "content": "动画和漫画已经伴随着一代又一代的孩子成长，而且也成为许多人不可割舍的一部分，当代大学生对动漫已经产生了非同寻常的感情。许多有画漫画的天赋，但是却找不到一个平台来让他们展现自己的天赋。同时，《秦时明月》、《画江湖》等多部国产动漫的热播，给我国一直处于萎靡状态的动漫事业注入了新鲜血液，更是掀起了大家对动漫的喜爱的一阵热风。我们和风日语社以此为契机开展动漫大赛暨画展，希望广大动漫爱好者能够踊跃参与。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1460125187000,
            "likeCount": 8,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 20155,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 800,
                "url": "http://qiniu.myfriday.cn/o_1afr42dd41vd8fp1qvm1vrv1pli7.jpg",
                "width": 600
            }],
            "readCount": 136583,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 19902,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "动漫大赛暨画展",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "大学生和风日语社",
            "weight": 0
        }, {
            "activitySite": "",
            "activityTime": 1459987200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 11,
            "content": "",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1460010462000,
            "likeCount": 27,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 20082,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 653,
                "url": "",
                "width": 490
            }],
            "readCount": 173991,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 19829,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "",
            "weight": 0
        }, {
            "activitySite": "全国高校",
            "activityTime": 1458835200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 15,
            "content": "国际大学生iCAN创新创业大赛，是由国际iCAN联盟、教育部创新方法教学指导分委员会和全球华人微纳米分子系统学会联合主办、北京大学承办的面向大学生创新创业的年度竞赛。iCAN大赛秉承“自信、坚持、梦想”精神，倡导科技创新创业服务社会、改善人类生活，引导和激励高校学生勇于创新，发现和培养一批有作为、有潜力的优秀青年创新创业人才，促进和加强以物联网、智能硬件等为代表的高科技领域的产学研结合，推动高科技产业的发展，为高科技创新创业搭建国际交流平台。报名链接：http://submit.ican-contest.org/index.php/Home/User/login_m.html",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1459240915000,
            "likeCount": 6,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 18233,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 800,
                "url": "http://77wdxv.com2.z0.glb.qiniucdn.com/treehole/club/20160329.jpg",
                "width": 600
            }],
            "readCount": 125453,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 17980,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "第十届国际大学生iCAN创新创业大赛",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "国际大学生iCAN创新创业大赛组委会",
            "weight": 0
        }, {
            "activitySite": "计算机102，一餐东门，听雨林，新浪微博",
            "activityTime": 1458950400000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 3,
            "content": "为贯彻落实团中央《关于开展高校共青团学习宣传贯彻习近平总书记系列重要讲话精神“四进四信”活动的通知》要求，以及团省委相关文件精神，深入推进社会主义核心价值观融入大学生修身教育全过程，加强基层团组织建设，强化共青团主题教育活动，增强共青团组织的凝聚力和号召力。以“四进”为手段，以“四信”为目标，即通过“进支部、进社团、进网络、进团课”，我协会开展本次活动，树立对党的科学理论的“信仰”，坚定走中国特色社会主义道路实现中国梦的“信念”，增强对党和政府的“信任”，增进对习近平同志为总书记的党中央的“信赖”。\n活动内容：1、观影写感活；2、“我与祖国共奋”宣传；3、户外拓展—撕名牌；4、阳光跟帖",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1458913528000,
            "likeCount": 6,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 16452,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 898,
                "url": "http://qiniu.myfriday.cn/o_1aemvpomsof8nfte0q1sbj1u4o7.jpg",
                "width": 673
            }],
            "readCount": 136795,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 16199,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "先行“四进四信” 筑梦美丽中国",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "大学生反邪教协会",
            "weight": 0
        }, {
            "activitySite": "hpu一餐东门",
            "activityTime": 1458349200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 12,
            "content": "你是否碰到这样的电脑问题！电脑越用越慢？电脑突然毫无反应，严重影响学习和娱乐？病毒肆虐，电脑频繁中毒？跑去维修中心，费用昂贵且服务态度不好？那么，赶快行动吧！！！\n\n       我们e佰计算机协会特开展义务维修和清洗电脑活动，以实际行动为同学们排忧解难，心动不如行动，小伙伴们，拿起你的笔记本，来我们的活动现场吧！！！\n\n具体服务内容包括：\n硬件方面：笔记本、台式灰尘清除、硬件检测及部分硬件维修等。\n软件方面：病毒查杀、系统重装、系统优化、病毒及部分插件免疫、蓝屏、黑屏、解决不了上网的问题等。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1458216239000,
            "likeCount": 19,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 12827,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 902,
                "url": "http://qiniu.myfriday.cn/o_1ae27cfpbhon2jc5fn1v7v1f097.jpg",
                "width": 677
            }],
            "readCount": 119606,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 12574,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "电脑义务维修活动",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学e佰计算机协会",
            "weight": 0
        }, {
            "activitySite": "二教2402",
            "activityTime": 1451473200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 9,
            "content": "时光荏苒，岁月如歌。美好的2015渐行渐远，2016年的步伐已将来临，在元旦来临之际，由机械与动力工程学院宣传中心、青年志愿者协会及大学生新月文艺团联合举办的元旦晚会拉开帷幕。晚会上会有动听的歌声和搞笑的小品，当然这里还准备了水果、瓜子等。晚会还会举行抽奖活动，自行车一辆、精美水杯若干，现场抽奖，随抽即可带走。30号晚上2402不见不散！关注零元抢购官方微信公众号【lyqg2015】,还有更多大奖（2部手机、20辆自行车和更多新年红包）等你哦！",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1451346597000,
            "likeCount": 10,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 12318,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 338,
                "url": "http://qiniu.myfriday.cn/o_1a7m0p6141mf113u51o4m1sje1grr7.jpg",
                "width": 254
            }],
            "readCount": 683211,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 12065,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "机宣、新月、机械青协迎元旦联合晚会",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学机械学院宣传中心",
            "weight": 0
        }, {
            "activitySite": "河南理工大学一餐东门",
            "activityTime": 1450573200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 13,
            "content": "你是否碰到这样的电脑问题！电脑越用越慢？电脑突然毫无反应，严重影响学习和娱乐？病毒肆虐，电脑频繁中毒？跑去维修中心，费用昂贵且服务态度不好？那么，赶快行动吧！！！\n\n       我们e佰计算机协会特开展义务维修和清洗电脑活动，以实际行动为同学们排忧解难，心动不如行动，小伙伴们，拿起你的笔记本，来我们的活动现场吧！！！\n\n具体服务内容包括：\n硬件方面：笔记本、台式灰尘清除、硬件检测及部分硬件维修等。\n软件方面：病毒查杀、系统重装、系统优化、病毒及部分插件免疫、蓝屏、黑屏、解决不了上网的问题等。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1450434088000,
            "likeCount": 32,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 12196,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 902,
                "url": "http://qiniu.myfriday.cn/o_1a6q92o2nv4a1h4c96poag7h7.jpg",
                "width": 677
            }],
            "readCount": 282303,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11943,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "电脑义务维修",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学e佰计算机协会",
            "weight": 0
        }, {
            "activitySite": "文综楼110",
            "activityTime": 1449921600000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 10,
            "content": "动漫作为一种最普遍的艺术表现形式，深受大学生们的喜爱。一部动漫里面精彩的片段往往令人魂牵梦绕，有的让你追忆曾经的过往，有的让你畅想未来的美好。为鼓励广大学生在欣赏动漫中大胆开口，为丰富同学们的课余生活，满足同学们更切实地体验日本声优魅力的愿望，提高日语口语水平，真情演绎，秀出真我，大学生和风日语社日语配音大赛期待你的参与！活动活动：现场配音。填过报名表的队伍将按照自己已选择的视频现场配音。可自己剪切并消音，自主选择的视频于11月26日之前发至社团邮箱。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1449917206000,
            "likeCount": 13,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 12097,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 417,
                "url": "http://qiniu.myfriday.cn/o_1a6aspiri14u1gp6130uo9ragi9.png",
                "width": 312
            }],
            "readCount": 237993,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11844,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "日语配音体验",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "大学生和风日语社",
            "weight": 0
        },
{
            "activitySite": "工程训练中心3D打印室",
            "activityTime": 1450573200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 1,
            "content": "近距离体验3D打印\n20号 周日，大学生3D动力协会面向全校师生举办“一元--走进3D打印活动！”        \n         只需一块钱，就可以直接体验3D打印技术！\n         零门槛 现场学！实时直接操作3D打印机 打印作品留念个人收藏 一克五毛的打印材料我们掏！打印现场更有3D酷炫视频、技术讲解！福利多多~等你参与~[呲牙][呲牙]\n         详情加入qq群459209938讨论，了解详情！周二下午-一餐东门-3D协会，现场报名，与你不见不散！",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1449914404000,
            "likeCount": 7,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 12096,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 800,
                "url": "http://qiniu.myfriday.cn/o_1a6apvfqp1g191m1712j71itj14uv7.jpg",
                "width": 600
            }],
            "readCount": 4215,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11843,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "一元——走进3D打印",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "3D动力社团",
            "weight": 0
        },
{
            "activitySite": "河南理工大学小礼堂",
            "activityTime": 1449226800000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 8,
            "content": "河南理工大学第七届\"大爱杯\"大学生志愿者风采大赛，历时3个多月，经过初赛的审核、复赛的现场展示，最终有八支队伍从四十多支队伍中脱颖而出，晚会上，让我们一起看平凡的志愿者成就不平凡志愿活动。“奉献、友爱、互助、进步”是我们的口号。本周五19:00小礼堂，一起看8支团队一展志愿风采。\n     激烈赛事即将开始，一起为我们的青春呐喊！",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1449142176000,
            "likeCount": 11,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 11850,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 3927,
                "url": "http://qiniu.myfriday.cn/o_1a5jpd7t39p71ncm14r119j61rf69.jpg",
                "width": 2945
            }],
            "readCount": 93601,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11594,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "第七届\"大爱杯\"大学生志愿者风采大赛决赛",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学青年志愿者协会",
            "weight": 0
        },
{
            "activitySite": "理工大，体育馆，科技馆",
            "activityTime": 1450483200000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 7,
            "content": "1圣诞老人被坏人绑架了，我们需要通过比赛获得游戏线索，根据线索找到坏人\n2活动场地暂时设定为理工大，体育馆，太极体育中心，科技馆，商场\n3找到坏人之后，开始终极撕名牌，守卫我们的圣诞老人。\n4欢迎团体报名，报名范围理工大，师专，焦大\n5活动人数限制10男10女。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1449053151000,
            "likeCount": 10,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 11804,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 641,
                "url": "http://qiniu.myfriday.cn/o_1a5h497ed5sr1o61lgt2gfni17.jpeg",
                "width": 480
            }],
            "readCount": 10907,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11548,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "聚了么五期：平安夜之穿越时空的爱恋",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "聚了么",
            "weight": 0
        },
{
            "activitySite": "河南理工大学学苑餐厅东门",
            "activityTime": 1449273600000,
            "adSpaceId": 0,
            "anonymous": false,
            "category": 60,
            "comments": 2,
            "content": "曾经有一个参加法制宣传周活动的机会放在我的面前，我没有去珍惜，直到失去后我才追悔莫及。人生最痛苦的事莫过于此。如果一切可以重来，我会对着天空大喊：‘我要参加法制宣传周活动，如果能够让我选择礼品的话，我希望是美女。 法制宣传周活动12.05号这周六将在学苑餐厅东门举办，届时欢迎各位美女帅哥前来参加。本次活动非常好玩，既能享受一个愉快的周末，又能增加自己的法律知识，游戏好玩，美女养眼，帅哥酷炫，福利漫天你们还在等什么，快来学苑餐厅一起happy吧，周六与你不见不散。",
            "delete": false,
            "icon": "http://qiniu.myfriday.cn/treehole/defalut/xh_icon-qgzq.png",
            "isCampusMessage": 0,
            "isShowTime": true,
            "issueTime": 1448951347000,
            "likeCount": 10,
            "linkList": [{
                "linkId": 0
            }],
            "linkType": 0,
            "messageId": 11750,
            "myCollect": false,
            "myLike": 0,
            "mySchool": false,
            "mySupport": 0,
            "plateId": 6,
            "plateName": "校内 校园活动",
            "poster": false,
            "publisher": "社团活动",
            "publisherType": 31,
            "qiniuImgBOs": [{
                "height": 837,
                "url": "http://qiniu.myfriday.cn/o_1a5e3g7hu13iea6o1n3a1hmdp3u7.jpg",
                "width": 628
            }],
            "readCount": 30048,
            "schoolId": 180028,
            "showTime": true,
            "source": "web_club",
            "sourceId": 11494,
            "studentIdTemp": 0,
            "support": 0,
            "tag": 0,
            "title": "机械&数信 法制宣传周",
            "titleFontColor": "#333333",
            "totalScoreTemp": 0,
            "unit": "河南理工大学数信学院宣传组",
            "weight": 0
        }

*/